-- DROPS PREVIOUS TRACKER_DB IF ALREADY EXISTS--
DROP DATABASE IF EXISTS tracker_db;
--CREATES TRACKER DATABASE--
CREATE DATABASE tracker_db;
--USE DATABASE--
USE tracker_db;
--CREATE DEPARTMENT TABLE--
CREATE TABLE department (
  id INT UNSIGNED NOT NULL PRIMARY KEY,
  name VARCHAR(30),
  PRIMARY KEY (id)
);
--CREATE ROLE TABLE--
CREATE TABLE role (
  id INT UNSIGNED NOT NULL PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL,
  department_id INT UNSIGNED NOT NULL
);
--CREATE EMPLOYEE TABLE 

CREATE TABLE employee (
  id INT UNSIGNED NOT NULL PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL, 
  last_name VARCHAR(30) NOT NULL, 
  role_id INT UNSIGNED NOT NULL,
  manager_id INT UNSIGNED, 
);
